# Generated by Django 5.2.7 on 2025-10-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0002_lesson_is_published_lesson_slug_lesson_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, to='lmsApp.lesson'),
        ),
    ]
