# Generated by Django 5.2.7 on 2025-10-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0005_lesson_is_published_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='lmsApp.category'),
        ),
    ]
