# Generated by Django 5.2.7 on 2025-10-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0006_remove_course_category_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='what_you_will_learn',
            field=models.TextField(blank=True, help_text='Enter one learning outcome per line.', null=True),
        ),
    ]
