# Generated by Django 5.2.7 on 2025-10-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0008_course_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='A short biography of the user.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text="URL for the user's profile picture.", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='receives_new_course_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='receives_progress_reminders',
            field=models.BooleanField(default=True),
        ),
    ]
