# Generated by Django 5.2.7 on 2025-10-12 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0013_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per month in NGN.', max_digits=10)),
                ('max_members', models.PositiveIntegerField(help_text='Maximum number of members allowed in the team.')),
                ('description', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, help_text='Enter one feature per line. This will be displayed as a list.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Is the subscription for this team currently active?'),
        ),
        migrations.AddField(
            model_name='team',
            name='subscription_ends',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lmsApp.subscriptionplan'),
        ),
    ]
