# Generated by Django 5.2.7 on 2025-10-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0014_subscriptionplan_team_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='address',
            field=models.TextField(blank=True, help_text='Registered business address for invoicing.', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number for the team/company.', max_length=20, null=True),
        ),
    ]
