# Generated by Django 5.2.7 on 2025-10-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0015_team_address_team_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_b2b_member',
            field=models.BooleanField(default=False),
        ),
    ]
