# Generated by Django 5.2.7 on 2025-10-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0016_customuser_is_b2b_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_invited',
            field=models.BooleanField(default=False),
        ),
    ]
